#!/usr/bin/env sh
cd "$(dirname "$0")"/../Resources
if [ -f ./vmargs.txt ]
then
	vmargs=`cat vmargs.txt`
	./runtime/bin/java $vmargs $@
	exit $?
else
	echo "No arguments file found (./Contents/Resources/vmargs.txt) for the VM, exiting." 1>&2
	exit 255
fi